// Canonical DryUI component names + categories. Mirrors the named exports
// from @dryui/ui's src/index.ts and the `category` field in each component's
// .meta.ts. Used by the feedback widget's "Add component" picker — keep in
// sync if the public surface changes.

export type ComponentCategory =
	| 'action'
	| 'display'
	| 'feedback'
	| 'form'
	| 'input'
	| 'interaction'
	| 'layout'
	| 'navigation'
	| 'overlay'
	| 'utility'
	| 'visual';

export const CATEGORY_ORDER: ComponentCategory[] = [
	'action',
	'form',
	'input',
	'navigation',
	'overlay',
	'layout',
	'display',
	'feedback',
	'visual',
	'interaction',
	'utility'
];

export const CATEGORY_LABELS: Record<ComponentCategory, string> = {
	action: 'Action',
	form: 'Form',
	input: 'Input',
	navigation: 'Navigation',
	overlay: 'Overlay',
	layout: 'Layout',
	display: 'Display',
	feedback: 'Feedback',
	visual: 'Visual',
	interaction: 'Interaction',
	utility: 'Utility'
};

export const COMPONENT_CATEGORIES: Record<string, ComponentCategory> = {
	Accordion: 'display',
	Adjust: 'visual',
	Alert: 'feedback',
	AlertDialog: 'overlay',
	AlphaSlider: 'input',
	AppFrame: 'layout',
	AspectRatio: 'layout',
	Aurora: 'layout',
	Avatar: 'display',
	Backdrop: 'overlay',
	Badge: 'display',
	Beam: 'visual',
	BorderBeam: 'visual',
	Breadcrumb: 'navigation',
	Button: 'action',
	ButtonGroup: 'action',
	Calendar: 'form',
	Carousel: 'display',
	Chart: 'display',
	ChatThread: 'display',
	Checkbox: 'input',
	Chip: 'action',
	ChipGroup: 'layout',
	ChromaticAberration: 'visual',
	ChromaticShift: 'visual',
	Clipboard: 'action',
	CodeBlock: 'display',
	Collapsible: 'display',
	ColorPicker: 'input',
	Combobox: 'form',
	CommandPalette: 'overlay',
	Container: 'layout',
	ContextMenu: 'overlay',
	DataGrid: 'display',
	DateField: 'form',
	DatePicker: 'form',
	DateRangePicker: 'form',
	DateTimeInput: 'input',
	DescriptionList: 'display',
	Diagram: 'display',
	Dialog: 'overlay',
	Displacement: 'visual',
	DragAndDrop: 'interaction',
	Drawer: 'overlay',
	DropZone: 'input',
	DropdownMenu: 'overlay',
	Enter: 'display',
	Exit: 'display',
	Field: 'form',
	Fieldset: 'form',
	FileSelect: 'input',
	FileUpload: 'input',
	FlipCard: 'display',
	FloatButton: 'action',
	FocusTrap: 'utility',
	FormatBytes: 'display',
	FormatDate: 'display',
	FormatNumber: 'display',
	Gauge: 'display',
	Glass: 'visual',
	Glow: 'visual',
	GodRays: 'visual',
	GradientMesh: 'visual',
	Halftone: 'visual',
	Heading: 'display',
	Hotkey: 'utility',
	HoverCard: 'overlay',
	Icon: 'display',
	IconSwap: 'display',
	Image: 'display',
	ImageComparison: 'display',
	InfiniteScroll: 'display',
	Input: 'input',
	InputGroup: 'input',
	Kbd: 'display',
	Label: 'form',
	Link: 'navigation',
	LinkPreview: 'overlay',
	List: 'display',
	Listbox: 'input',
	LogoMark: 'display',
	Map: 'display',
	MarkdownRenderer: 'display',
	Marquee: 'display',
	MaskReveal: 'visual',
	MegaMenu: 'navigation',
	Menubar: 'navigation',
	Motion: 'display',
	MultiSelectCombobox: 'form',
	NavigationMenu: 'navigation',
	Noise: 'layout',
	NotificationCenter: 'overlay',
	NumberInput: 'input',
	Numeric: 'display',
	OptionPicker: 'input',
	Pagination: 'navigation',
	PhoneInput: 'input',
	PinInput: 'input',
	Popover: 'overlay',
	Portal: 'utility',
	Progress: 'feedback',
	ProgressRing: 'feedback',
	PromptInput: 'input',
	QRCode: 'display',
	RadioGroup: 'input',
	RangeCalendar: 'form',
	Rating: 'input',
	RelativeTime: 'display',
	Reveal: 'display',
	RichTextEditor: 'input',
	ScrollArea: 'layout',
	ScrollToTop: 'action',
	SegmentedControl: 'form',
	Select: 'form',
	Separator: 'layout',
	ShaderCanvas: 'visual',
	Shimmer: 'visual',
	Sidebar: 'navigation',
	Skeleton: 'feedback',
	Slider: 'input',
	Spacer: 'layout',
	Sparkline: 'display',
	Spinner: 'feedback',
	Splitter: 'layout',
	Spotlight: 'display',
	Stagger: 'display',
	StarRating: 'display',
	Stepper: 'navigation',
	Svg: 'utility',
	Table: 'display',
	TableOfContents: 'navigation',
	Tabs: 'navigation',
	Tag: 'display',
	TagsInput: 'input',
	Text: 'display',
	Textarea: 'input',
	ThemeToggle: 'action',
	TimeInput: 'input',
	Timeline: 'display',
	Toast: 'feedback',
	Toggle: 'action',
	ToggleGroup: 'action',
	Toolbar: 'navigation',
	Tooltip: 'overlay',
	Tour: 'overlay',
	Transfer: 'input',
	Tree: 'display',
	TypingIndicator: 'display',
	Typography: 'display',
	VideoEmbed: 'display',
	VirtualList: 'display',
	VisuallyHidden: 'utility'
};

export const COMPONENT_NAMES = Object.keys(COMPONENT_CATEGORIES).sort() as readonly string[];
