// AUTO-GENERATED by scripts/extract-feedback-schemas.ts
// Re-run that script when DryUI component prop signatures change.

export type SchemaFieldType =
	| { kind: 'enum'; options: string[] }
	| { kind: 'boolean' }
	| { kind: 'number' }
	| { kind: 'string' }
	| { kind: 'snippet' };

export type SchemaField = {
	name: string;
	optional: boolean;
	type: SchemaFieldType;
};

export const COMPONENT_SCHEMAS: Record<string, SchemaField[]> = {
	AccordionItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	AccordionRoot: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	Adjust: [
		{ name: 'blur', optional: true, type: { kind: 'number' } },
		{ name: 'brightness', optional: true, type: { kind: 'number' } },
		{ name: 'contrast', optional: true, type: { kind: 'number' } },
		{ name: 'grayscale', optional: true, type: { kind: 'number' } },
		{ name: 'hueRotate', optional: true, type: { kind: 'number' } },
		{ name: 'invert', optional: true, type: { kind: 'number' } },
		{ name: 'saturate', optional: true, type: { kind: 'number' } },
		{ name: 'sepia', optional: true, type: { kind: 'number' } }
	],
	Alert: [
		{ name: 'dismissible', optional: true, type: { kind: 'boolean' } },
		{ name: 'onDismiss', optional: true, type: { kind: 'snippet' } }
	],
	AlertDialogRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	AlphaSliderInput: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	AppFrame: [
		{ name: 'actions', optional: true, type: { kind: 'snippet' } },
		{ name: 'title', optional: true, type: { kind: 'string' } }
	],
	AspectRatio: [{ name: 'ratio', optional: true, type: { kind: 'number' } }],
	Aurora: [
		{
			name: 'colorSpace',
			optional: true,
			type: { kind: 'enum', options: ['srgb', 'oklch', 'oklab'] }
		},
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'layerOpacity', optional: true, type: { kind: 'number' } },
		{ name: 'motion', optional: true, type: { kind: 'enum', options: ['auto', 'never'] } },
		{
			name: 'palette',
			optional: true,
			type: { kind: 'enum', options: ['sunrise', 'ocean', 'forest', 'cosmic'] }
		},
		{ name: 'speed', optional: true, type: { kind: 'enum', options: ['slow', 'normal', 'fast'] } },
		{ name: 'waviness', optional: true, type: { kind: 'number' } }
	],
	Avatar: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'alt', optional: true, type: { kind: 'string' } },
		{ name: 'badge', optional: true, type: { kind: 'snippet' } },
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{ name: 'shape', optional: true, type: { kind: 'enum', options: ['circle', 'square'] } },
		{ name: 'src', optional: true, type: { kind: 'string' } },
		{
			name: 'status',
			optional: true,
			type: { kind: 'enum', options: ['online', 'offline', 'busy', 'away'] }
		}
	],
	Backdrop: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'invisible', optional: true, type: { kind: 'boolean' } }
	],
	Badge: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['solid', 'outline', 'soft', 'dot'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'numeric', optional: true, type: { kind: 'boolean' } },
		{ name: 'pulse', optional: true, type: { kind: 'boolean' } }
	],
	Beam: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	BreadcrumbLink: [
		{ name: 'current', optional: true, type: { kind: 'boolean' } },
		{ name: 'href', optional: true, type: { kind: 'string' } }
	],
	Button: [
		{
			name: 'variant',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'solid',
					'outline',
					'ghost',
					'soft',
					'secondary',
					'link',
					'bare',
					'trigger',
					'nav',
					'tab',
					'toggle',
					'pill'
				]
			}
		},
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['sm', 'md', 'lg', 'icon', 'icon-sm', 'icon-lg'] }
		},
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'href', optional: true, type: { kind: 'string' } },
		{ name: 'optical', optional: true, type: { kind: 'enum', options: ['auto', 'off'] } },
		{ name: 'rel', optional: true, type: { kind: 'string' } },
		{ name: 'target', optional: true, type: { kind: 'string' } }
	],
	ButtonGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	CalendarGridButton: [{ name: 'hideHeader', optional: true, type: { kind: 'boolean' } }],
	CalendarNavButton: [
		{ name: 'direction', optional: false, type: { kind: 'enum', options: ['prev', 'next'] } }
	],
	CalendarRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	CardContent: [{ name: 'noPadding', optional: true, type: { kind: 'boolean' } }],
	CardRoot: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['default', 'elevated', 'interactive'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['default', 'sm'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'as', optional: true, type: { kind: 'enum', options: ['div', 'button'] } },
		{ name: 'bordered', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal'] }
		},
		{ name: 'selected', optional: true, type: { kind: 'boolean' } }
	],
	CarouselButtonThumbnails: [
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['bottom', 'left', 'right'] }
		}
	],
	CarouselNavButton: [
		{ name: 'direction', optional: false, type: { kind: 'enum', options: ['prev', 'next'] } }
	],
	CarouselRoot: [
		{ name: 'loop', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	ChartArea: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'dotRadius', optional: true, type: { kind: 'number' } },
		{ name: 'showDots', optional: true, type: { kind: 'boolean' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } }
	],
	ChartBars: [{ name: 'radius', optional: true, type: { kind: 'number' } }],
	ChartDonut: [
		{ name: 'innerRadius', optional: true, type: { kind: 'number' } },
		{ name: 'label', optional: true, type: { kind: 'snippet' } },
		{ name: 'outerRadius', optional: true, type: { kind: 'number' } }
	],
	ChartHorizontalBar: [{ name: 'radius', optional: true, type: { kind: 'number' } }],
	ChartLine: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'dotRadius', optional: true, type: { kind: 'number' } },
		{ name: 'showDots', optional: true, type: { kind: 'boolean' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } }
	],
	ChartRoot: [
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'summary', optional: true, type: { kind: 'string' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	ChartStackedBar: [{ name: 'radius', optional: true, type: { kind: 'number' } }],
	ChartYAxis: [{ name: 'ticks', optional: true, type: { kind: 'number' } }],
	ChatThread: [
		{ name: 'messageCount', optional: false, type: { kind: 'number' } },
		{ name: 'scrollKey', optional: true, type: { kind: 'number' } }
	],
	CheckboxInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'checked', optional: true, type: { kind: 'boolean' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'indeterminate', optional: true, type: { kind: 'boolean' } }
	],
	ChipGroupButtonItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	ChipGroupRoot: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'gap', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'justify',
			optional: true,
			type: { kind: 'enum', options: ['start', 'center', 'end', 'between'] }
		},
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	ChromaticAberration: [
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{ name: 'offset', optional: true, type: { kind: 'number' } }
	],
	ChromaticShift: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{ name: 'channels', optional: true, type: { kind: 'enum', options: ['rgb', 'rb'] } },
		{ name: 'offset', optional: true, type: { kind: 'number' } },
		{
			name: 'trigger',
			optional: true,
			type: { kind: 'enum', options: ['hover', 'always', 'none'] }
		}
	],
	Clipboard: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'timeout', optional: true, type: { kind: 'number' } }
	],
	CloseButtonBase: [{ name: 'label', optional: true, type: { kind: 'string' } }],
	CodeBlockButton: [
		{ name: 'code', optional: false, type: { kind: 'string' } },
		{ name: 'language', optional: true, type: { kind: 'string' } },
		{ name: 'linkResolver', optional: true, type: { kind: 'snippet' } },
		{ name: 'showCopyButton', optional: true, type: { kind: 'boolean' } },
		{ name: 'showLineNumbers', optional: true, type: { kind: 'boolean' } }
	],
	CollapsibleRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } }
	],
	ColorPickerArea: [
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	ColorPickerChannelInput: [
		{ name: 'channel', optional: false, type: { kind: 'enum', options: ['h', 's', 'v'] } }
	],
	ColorPickerInput: [
		{ name: 'format', optional: true, type: { kind: 'enum', options: ['hex', 'rgb', 'hsl'] } }
	],
	ColorPickerRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'alpha', optional: true, type: { kind: 'number' } },
		{ name: 'areaHeight', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	ColorPickerSwatch: [{ name: 'color', optional: true, type: { kind: 'string' } }],
	ComboboxContent: [
		{ name: 'loading', optional: true, type: { kind: 'boolean' } },
		{ name: 'loadingContent', optional: true, type: { kind: 'snippet' } },
		{ name: 'offset', optional: true, type: { kind: 'number' } }
	],
	ComboboxGroup: [{ name: 'label', optional: false, type: { kind: 'string' } }],
	ComboboxInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'leading', optional: true, type: { kind: 'snippet' } },
		{ name: 'trailing', optional: true, type: { kind: 'snippet' } }
	],
	ComboboxInputRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	ComboboxItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'index', optional: false, type: { kind: 'number' } }
	],
	CommandPaletteDialogRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	CommandPaletteGroup: [{ name: 'heading', optional: true, type: { kind: 'string' } }],
	CommandPaletteInput: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	CommandPaletteItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'onSelect', optional: true, type: { kind: 'snippet' } }
	],
	Container: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['sm', 'md', 'lg', 'xl', 'full'] }
		},
		{ name: 'padding', optional: true, type: { kind: 'boolean' } }
	],
	ContextMenuItem: [{ name: 'disabled', optional: true, type: { kind: 'boolean' } }],
	ContextMenuRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	DataGridButtonExpandTrigger: [{ name: 'rowId', optional: false, type: { kind: 'string' } }],
	DataGridButtonInputColumn: [
		{ name: 'filterable', optional: true, type: { kind: 'boolean' } },
		{ name: 'header', optional: true, type: { kind: 'snippet' } },
		{ name: 'key', optional: false, type: { kind: 'string' } },
		{ name: 'pinned', optional: true, type: { kind: 'boolean' } },
		{ name: 'resizable', optional: true, type: { kind: 'boolean' } },
		{ name: 'sortable', optional: true, type: { kind: 'boolean' } }
	],
	DataGridExpandableRow: [
		{ name: 'expandable', optional: false, type: { kind: 'snippet' } },
		{ name: 'rowId', optional: false, type: { kind: 'string' } }
	],
	DataGridInputSelectCell: [
		{ name: 'rowId', optional: false, type: { kind: 'string' } },
		{ name: 'rowLabel', optional: true, type: { kind: 'string' } }
	],
	DataGridRow: [{ name: 'rowId', optional: true, type: { kind: 'string' } }],
	DateFieldInputRoot: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	DateFieldSeparator: [{ name: 'separator', optional: true, type: { kind: 'string' } }],
	DateRangePickerButtonTrigger: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	DateRangePickerContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	DateRangePickerRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	DateTimeInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	DatepickerButtonTrigger: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } }
	],
	DatepickerContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	DatepickerInputRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	Diagram: [
		{ name: 'fit', optional: true, type: { kind: 'enum', options: ['contain', 'native'] } },
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	DialogRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Displacement: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{ name: 'scale', optional: true, type: { kind: 'number' } },
		{
			name: 'turbulence',
			optional: true,
			type: { kind: 'enum', options: ['gentle', 'medium', 'rough'] }
		}
	],
	DragAndDropGroup: [{ name: 'onMove', optional: false, type: { kind: 'snippet' } }],
	DragAndDropHandle: [{ name: 'index', optional: false, type: { kind: 'number' } }],
	DragAndDropItem: [{ name: 'index', optional: false, type: { kind: 'number' } }],
	DrawerBody: [{ name: 'padding', optional: true, type: { kind: 'boolean' } }],
	DrawerRoot: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{
			name: 'side',
			optional: true,
			type: { kind: 'enum', options: ['top', 'right', 'bottom', 'left'] }
		}
	],
	DropZone: [
		{ name: 'accept', optional: true, type: { kind: 'string' } },
		{ name: 'onDrop', optional: true, type: { kind: 'snippet' } }
	],
	DropdownMenuContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	DropdownMenuItem: [{ name: 'disabled', optional: true, type: { kind: 'boolean' } }],
	DropdownMenuRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Enter: [
		{ name: 'as', optional: true, type: { kind: 'string' } },
		{ name: 'duration', optional: true, type: { kind: 'string' } },
		{ name: 'index', optional: true, type: { kind: 'number' } }
	],
	FieldRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'error', optional: true, type: { kind: 'string' } },
		{ name: 'nestRadius', optional: true, type: { kind: 'boolean' } },
		{ name: 'required', optional: true, type: { kind: 'boolean' } }
	],
	FileSelectButtonTrigger: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	FileSelectRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'accept', optional: true, type: { kind: 'string' } },
		{ name: 'directory', optional: true, type: { kind: 'boolean' } },
		{ name: 'onrequest', optional: true, type: { kind: 'snippet' } }
	],
	FileSelectValue: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	FileUploadButtonItemDelete: [{ name: 'index', optional: false, type: { kind: 'number' } }],
	FileUploadButtonTrigger: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	FileUploadDropzone: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	FileUploadInputRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'accept', optional: true, type: { kind: 'string' } },
		{ name: 'maxFiles', optional: true, type: { kind: 'number' } },
		{ name: 'maxSize', optional: true, type: { kind: 'number' } },
		{ name: 'multiple', optional: true, type: { kind: 'boolean' } },
		{ name: 'onFilesChange', optional: true, type: { kind: 'snippet' } }
	],
	FileUploadItem: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'index', optional: false, type: { kind: 'number' } }
	],
	FileUploadList: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	FlipCardRoot: [
		{
			name: 'direction',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'flipped', optional: true, type: { kind: 'boolean' } },
		{ name: 'trigger', optional: true, type: { kind: 'enum', options: ['hover', 'click'] } }
	],
	FloatButtonRoot: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['bottom-right', 'bottom-left'] }
		}
	],
	FloatButtonTrigger: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	FocusTrap: [
		{ name: 'active', optional: true, type: { kind: 'boolean' } },
		{ name: 'initialFocus', optional: true, type: { kind: 'string' } },
		{ name: 'returnFocus', optional: true, type: { kind: 'boolean' } }
	],
	FormatBytes: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{
			name: 'display',
			optional: true,
			type: { kind: 'enum', options: ['short', 'long', 'narrow'] }
		},
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'unit', optional: true, type: { kind: 'enum', options: ['byte', 'bit'] } }
	],
	FormatDate: [
		{
			name: 'dateStyle',
			optional: true,
			type: { kind: 'enum', options: ['full', 'long', 'medium', 'short'] }
		},
		{ name: 'day', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{ name: 'era', optional: true, type: { kind: 'enum', options: ['long', 'short', 'narrow'] } },
		{ name: 'hour', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'hourCycle',
			optional: true,
			type: { kind: 'enum', options: ['h11', 'h12', 'h23', 'h24'] }
		},
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'minute', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'month',
			optional: true,
			type: { kind: 'enum', options: ['numeric', '2-digit', 'long', 'short', 'narrow'] }
		},
		{ name: 'second', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'timeStyle',
			optional: true,
			type: { kind: 'enum', options: ['full', 'long', 'medium', 'short'] }
		},
		{ name: 'timeZone', optional: true, type: { kind: 'string' } },
		{ name: 'timeZoneName', optional: true, type: { kind: 'enum', options: ['long', 'short'] } },
		{
			name: 'weekday',
			optional: true,
			type: { kind: 'enum', options: ['long', 'short', 'narrow'] }
		},
		{ name: 'year', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } }
	],
	FormatNumber: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{ name: 'currency', optional: true, type: { kind: 'string' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'maximumFractionDigits', optional: true, type: { kind: 'number' } },
		{ name: 'maximumSignificantDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumFractionDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumIntegerDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumSignificantDigits', optional: true, type: { kind: 'number' } },
		{
			name: 'notation',
			optional: true,
			type: { kind: 'enum', options: ['standard', 'scientific', 'engineering', 'compact'] }
		},
		{
			name: 'type',
			optional: true,
			type: { kind: 'enum', options: ['decimal', 'currency', 'percent', 'unit'] }
		},
		{ name: 'unit', optional: true, type: { kind: 'string' } }
	],
	Gauge: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{ name: 'endAngle', optional: true, type: { kind: 'number' } },
		{ name: 'label', optional: true, type: { kind: 'snippet' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'startAngle', optional: true, type: { kind: 'number' } }
	],
	Glass: [
		{ name: 'blur', optional: true, type: { kind: 'number' } },
		{ name: 'saturation', optional: true, type: { kind: 'number' } },
		{ name: 'tint', optional: true, type: { kind: 'string' } }
	],
	Glow: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'blendMode', optional: true, type: { kind: 'string' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'radius', optional: true, type: { kind: 'number' } }
	],
	GodRays: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'blendMode', optional: true, type: { kind: 'string' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'rayCount', optional: true, type: { kind: 'number' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } }
	],
	GradientMesh: [
		{ name: 'interactive', optional: true, type: { kind: 'boolean' } },
		{ name: 'speed', optional: true, type: { kind: 'enum', options: ['slow', 'normal', 'fast'] } }
	],
	Halftone: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{
			name: 'dotSize',
			optional: true,
			type: { kind: 'enum', options: ['fine', 'medium', 'coarse'] }
		},
		{ name: 'opacity', optional: true, type: { kind: 'number' } }
	],
	Heading: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'display'] } },
		{
			name: 'maxMeasure',
			optional: true,
			type: { kind: 'enum', options: ['narrow', 'default', 'wide'] }
		}
	],
	HoverCardContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	HoverCardTrigger: [{ name: 'href', optional: true, type: { kind: 'string' } }],
	Icon: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg', 'xl'] }
		},
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['primary', 'muted', 'current'] }
		},
		{ name: 'label', optional: true, type: { kind: 'string' } }
	],
	Image: [
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{ name: 'fallbackSnippet', optional: true, type: { kind: 'snippet' } }
	],
	ImageComparison: [
		{ name: 'after', optional: false, type: { kind: 'snippet' } },
		{ name: 'before', optional: false, type: { kind: 'snippet' } },
		{ name: 'handle', optional: true, type: { kind: 'snippet' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'position', optional: true, type: { kind: 'number' } }
	],
	InfiniteScroll: [{ name: 'onLoadMore', optional: false, type: { kind: 'snippet' } }],
	Input: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'ghost'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	InputGroupInput: [{ name: 'value', optional: true, type: { kind: 'string' } }],
	InputGroupRoot: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'invalid', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	InputGroupSelect: [{ name: 'value', optional: true, type: { kind: 'string' } }],
	Label: [{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }],
	Link: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'external', optional: true, type: { kind: 'boolean' } },
		{
			name: 'underline',
			optional: true,
			type: { kind: 'enum', options: ['always', 'hover', 'none'] }
		}
	],
	LinkPreviewContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	LinkPreviewRoot: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'closeDelay', optional: true, type: { kind: 'number' } },
		{ name: 'openDelay', optional: true, type: { kind: 'number' } }
	],
	LinkPreviewTrigger: [{ name: 'href', optional: false, type: { kind: 'string' } }],
	ListItem: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'interactive', optional: true, type: { kind: 'boolean' } },
		{ name: 'title', optional: true, type: { kind: 'string' } }
	],
	ListItemText: [
		{ name: 'primary', optional: true, type: { kind: 'snippet' } },
		{ name: 'secondary', optional: true, type: { kind: 'snippet' } }
	],
	ListRoot: [
		{ name: 'dense', optional: true, type: { kind: 'boolean' } },
		{ name: 'disablePadding', optional: true, type: { kind: 'boolean' } }
	],
	LogoMark: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['brand', 'neutral', 'error', 'warning', 'success', 'info'] }
		},
		{ name: 'alt', optional: true, type: { kind: 'string' } },
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['square', 'rounded', 'circle'] }
		},
		{ name: 'src', optional: true, type: { kind: 'string' } }
	],
	MapControls: [
		{ name: 'fullscreen', optional: true, type: { kind: 'boolean' } },
		{ name: 'navigation', optional: true, type: { kind: 'boolean' } },
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['top-left', 'top-right', 'bottom-left', 'bottom-right'] }
		}
	],
	MapLayer: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'id', optional: false, type: { kind: 'string' } },
		{ name: 'opacity', optional: true, type: { kind: 'number' } },
		{
			name: 'type',
			optional: false,
			type: { kind: 'enum', options: ['heatmap', 'polygon', 'fill', 'circle', 'line'] }
		}
	],
	MapMarker: [{ name: 'color', optional: true, type: { kind: 'string' } }],
	MapPopup: [
		{ name: 'closeButton', optional: true, type: { kind: 'boolean' } },
		{ name: 'closeOnClick', optional: true, type: { kind: 'boolean' } },
		{ name: 'maxWidth', optional: true, type: { kind: 'string' } }
	],
	MapRoot: [
		{ name: 'createMap', optional: true, type: { kind: 'snippet' } },
		{ name: 'mapStyle', optional: true, type: { kind: 'string' } },
		{ name: 'maxZoom', optional: true, type: { kind: 'number' } },
		{ name: 'minZoom', optional: true, type: { kind: 'number' } },
		{ name: 'zoom', optional: true, type: { kind: 'number' } }
	],
	MarkdownRenderer: [
		{ name: 'content', optional: false, type: { kind: 'string' } },
		{ name: 'dangerouslyAllowRawHtml', optional: true, type: { kind: 'boolean' } }
	],
	Marquee: [
		{
			name: 'direction',
			optional: true,
			type: { kind: 'enum', options: ['left', 'right', 'up', 'down'] }
		},
		{ name: 'fade', optional: true, type: { kind: 'boolean' } },
		{ name: 'gap', optional: true, type: { kind: 'string' } },
		{ name: 'pauseOnHover', optional: true, type: { kind: 'boolean' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } }
	],
	MaskReveal: [
		{ name: 'direction', optional: true, type: { kind: 'enum', options: ['in', 'out'] } },
		{ name: 'duration', optional: true, type: { kind: 'number' } },
		{ name: 'once', optional: true, type: { kind: 'boolean' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['circle', 'linear', 'diagonal', 'diamond'] }
		},
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	MegaMenuColumn: [{ name: 'title', optional: true, type: { kind: 'string' } }],
	MegaMenuLink: [
		{ name: 'description', optional: true, type: { kind: 'snippet' } },
		{ name: 'href', optional: true, type: { kind: 'string' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'rel', optional: true, type: { kind: 'string' } },
		{ name: 'target', optional: true, type: { kind: 'string' } },
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['button', 'submit', 'reset'] } }
	],
	MegaMenuPanel: [
		{ name: 'align', optional: true, type: { kind: 'enum', options: ['start', 'center', 'end'] } },
		{ name: 'fullWidth', optional: true, type: { kind: 'boolean' } }
	],
	MenuItem: [{ name: 'close', optional: false, type: { kind: 'snippet' } }],
	MenubarContent: [
		{ name: 'offset', optional: true, type: { kind: 'number' } },
		{
			name: 'placement',
			optional: true,
			type: { kind: 'enum', options: ['bottom', 'bottom-start', 'bottom-end'] }
		}
	],
	MenubarItem: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'onSelect', optional: true, type: { kind: 'snippet' } }
	],
	MultiSelectComboboxContent: [
		{ name: 'loading', optional: true, type: { kind: 'boolean' } },
		{ name: 'loadingContent', optional: true, type: { kind: 'snippet' } },
		{ name: 'offset', optional: true, type: { kind: 'number' } }
	],
	MultiSelectComboboxGroup: [{ name: 'label', optional: false, type: { kind: 'string' } }],
	MultiSelectComboboxInput: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	MultiSelectComboboxItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'textValue', optional: true, type: { kind: 'string' } }
	],
	MultiSelectComboboxRootInput: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'maxSelections', optional: true, type: { kind: 'number' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{ name: 'onvaluechange', optional: true, type: { kind: 'snippet' } },
		{ name: 'query', optional: true, type: { kind: 'string' } }
	],
	MultiSelectComboboxSelectionItem: [{ name: 'value', optional: false, type: { kind: 'string' } }],
	MultiSelectComboboxSelectionRemoveButton: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'label', optional: true, type: { kind: 'string' } }
	],
	NavArrowButton: [
		{ name: 'direction', optional: false, type: { kind: 'enum', options: ['prev', 'next'] } },
		{ name: 'label', optional: false, type: { kind: 'string' } }
	],
	NavigationMenuLink: [{ name: 'active', optional: true, type: { kind: 'boolean' } }],
	Noise: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{
			name: 'blend',
			optional: true,
			type: { kind: 'enum', options: ['soft-light', 'overlay', 'multiply'] }
		},
		{
			name: 'grain',
			optional: true,
			type: { kind: 'enum', options: ['fine', 'medium', 'coarse'] }
		},
		{ name: 'opacity', optional: true, type: { kind: 'number' } }
	],
	NotificationCenterGroup: [{ name: 'label', optional: false, type: { kind: 'string' } }],
	NotificationCenterItem: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['info', 'warning', 'critical'] }
		},
		{ name: 'action', optional: true, type: { kind: 'snippet' } },
		{ name: 'id', optional: false, type: { kind: 'string' } },
		{ name: 'read', optional: true, type: { kind: 'boolean' } }
	],
	NotificationCenterPanel: [
		{ name: 'offset', optional: true, type: { kind: 'number' } },
		{
			name: 'placement',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'top',
					'top-start',
					'top-end',
					'bottom',
					'bottom-start',
					'bottom-end',
					'left',
					'left-start',
					'left-end',
					'right',
					'right-start',
					'right-end'
				]
			}
		}
	],
	NotificationCenterRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	NumberInputButton: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	Numeric: [
		{ name: 'align', optional: true, type: { kind: 'enum', options: ['start', 'center', 'end'] } },
		{ name: 'minDigits', optional: true, type: { kind: 'number' } },
		{ name: 'stable', optional: true, type: { kind: 'boolean' } }
	],
	OptionPickerItem: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['default', 'compact', 'visual'] }
		},
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'layout', optional: true, type: { kind: 'enum', options: ['inline', 'stacked'] } },
		{ name: 'unavailable', optional: true, type: { kind: 'boolean' } }
	],
	OptionPickerPreview: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['default', 'preset', 'font', 'shape'] }
		},
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['circle', 'rounded', 'square', 'pill'] }
		}
	],
	OptionPickerRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	PaginationLinkButton: [{ name: 'page', optional: false, type: { kind: 'number' } }],
	PaginationNavButton: [
		{ name: 'direction', optional: false, type: { kind: 'enum', options: ['prev', 'next'] } }
	],
	PaginationRoot: [
		{ name: 'page', optional: true, type: { kind: 'number' } },
		{ name: 'totalPages', optional: false, type: { kind: 'number' } }
	],
	PhoneInputSelect: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'defaultCountry', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	PickerPopoverContent: [
		{
			name: 'dataAttribute',
			optional: false,
			type: { kind: 'enum', options: ['data-dp-content', 'data-drp-content'] }
		},
		{ name: 'offset', optional: true, type: { kind: 'number' } }
	],
	PinInputRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'length', optional: true, type: { kind: 'number' } },
		{ name: 'mask', optional: true, type: { kind: 'boolean' } },
		{ name: 'oncomplete', optional: true, type: { kind: 'snippet' } },
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['numeric', 'alphanumeric'] } }
	],
	PopoverContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	PopoverRoot: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Portal: [{ name: 'disabled', optional: true, type: { kind: 'boolean' } }],
	Progress: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['blue', 'green', 'red', 'yellow'] }
		},
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'showLabel', optional: true, type: { kind: 'enum', options: ['inside', 'outside'] } }
	],
	ProgressRing: [
		{ name: 'size', optional: true, type: { kind: 'number' } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['primary', 'gray', 'green', 'red', 'yellow'] }
		},
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'indeterminate', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } }
	],
	PromptInputButtonTextarea: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'onpromptsubmit', optional: true, type: { kind: 'snippet' } },
		{ name: 'submitLabel', optional: true, type: { kind: 'string' } }
	],
	QrCode: [
		{ name: 'size', optional: true, type: { kind: 'number' } },
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'bgColor', optional: true, type: { kind: 'string' } },
		{ name: 'fgColor', optional: true, type: { kind: 'string' } }
	],
	RadioGroup: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'required', optional: true, type: { kind: 'boolean' } }
	],
	RadioGroupItemInput: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	RangeCalendarRoot: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	RatingButtonInput: [
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'allowHalf', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'onValueChange', optional: true, type: { kind: 'enum', options: ['md'] } },
		{ name: 'readonly', optional: true, type: { kind: 'boolean' } }
	],
	RelativeTime: [
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'updateInterval', optional: true, type: { kind: 'number' } }
	],
	Reveal: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['fade', 'slide-up', 'scale-in', 'blur-up', 'mask-up'] }
		},
		{ name: 'delay', optional: true, type: { kind: 'number' } },
		{ name: 'duration', optional: true, type: { kind: 'number' } },
		{ name: 'once', optional: true, type: { kind: 'boolean' } },
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	RichTextEditorRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'readonly', optional: true, type: { kind: 'boolean' } }
	],
	ScrollArea: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal', 'both'] }
		}
	],
	ScrollToTopButton: [
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['bottom-right', 'bottom-left', 'bottom-center'] }
		},
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	SegmentedControlItemButton: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	SegmentedControlRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	SelectContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	SelectItem: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	SelectRootInput: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	SelectTriggerButton: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }
	],
	SelectValue: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	Separator: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['weak', 'strong', 'shadow'] }
		},
		{ name: 'decorative', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	ShaderCanvas: [
		{ name: 'aspectRatio', optional: true, type: { kind: 'string' } },
		{ name: 'fragmentShader', optional: true, type: { kind: 'string' } },
		{
			name: 'preset',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'gradient-flow',
					'particle-field',
					'wave-distortion',
					'mesh-gradient',
					'liquid-metal'
				]
			}
		},
		{ name: 'themeColors', optional: true, type: { kind: 'boolean' } }
	],
	Shimmer: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'duration', optional: true, type: { kind: 'number' } }
	],
	SidebarItem: [{ name: 'active', optional: true, type: { kind: 'boolean' } }],
	SidebarRoot: [
		{ name: 'collapsed', optional: true, type: { kind: 'boolean' } },
		{ name: 'side', optional: true, type: { kind: 'enum', options: ['left', 'right'] } }
	],
	Skeleton: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['text', 'circular', 'rectangular'] }
		},
		{ name: 'height', optional: true, type: { kind: 'string' } },
		{ name: 'width', optional: true, type: { kind: 'string' } }
	],
	SliderInput: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'pill'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'step', optional: true, type: { kind: 'number' } },
		{ name: 'valueLabel', optional: true, type: { kind: 'snippet' } }
	],
	Spacer: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'] }
		},
		{ name: 'axis', optional: true, type: { kind: 'enum', options: ['vertical', 'horizontal'] } }
	],
	Sparkline: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'filled', optional: true, type: { kind: 'boolean' } },
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'highlightLast', optional: true, type: { kind: 'boolean' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	Spinner: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'color', optional: true, type: { kind: 'enum', options: ['primary', 'current'] } },
		{ name: 'label', optional: true, type: { kind: 'string' } }
	],
	SplitterHandle: [{ name: 'index', optional: true, type: { kind: 'number' } }],
	SplitterPanel: [{ name: 'index', optional: true, type: { kind: 'number' } }],
	SplitterRoot: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Spotlight: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'followPointer', optional: true, type: { kind: 'boolean' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'radius', optional: true, type: { kind: 'number' } }
	],
	Stagger: [
		{ name: 'as', optional: true, type: { kind: 'string' } },
		{ name: 'step', optional: true, type: { kind: 'enum', options: ['section', 'word', 'letter'] } }
	],
	StarRatingRoot: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['filled', 'outlined'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'label', optional: true, type: { kind: 'string' } },
		{ name: 'stars', optional: false, type: { kind: 'number' } }
	],
	StepperRoot: [
		{ name: 'activeStep', optional: true, type: { kind: 'number' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	StepperSeparator: [{ name: 'step', optional: false, type: { kind: 'number' } }],
	StepperStepButton: [
		{ name: 'clickable', optional: true, type: { kind: 'boolean' } },
		{ name: 'error', optional: true, type: { kind: 'boolean' } },
		{ name: 'onclick', optional: true, type: { kind: 'snippet' } },
		{ name: 'step', optional: false, type: { kind: 'number' } }
	],
	Svg: [{ name: 'viewBox', optional: true, type: { kind: 'string' } }],
	TableHead: [{ name: 'scope', optional: true, type: { kind: 'enum', options: ['col', 'row'] } }],
	TableOfContentsRoot: [
		{ name: 'autoId', optional: true, type: { kind: 'boolean' } },
		{ name: 'headingSelector', optional: true, type: { kind: 'string' } },
		{ name: 'rootMargin', optional: true, type: { kind: 'string' } },
		{ name: 'selector', optional: true, type: { kind: 'string' } }
	],
	TabsContent: [{ name: 'value', optional: false, type: { kind: 'string' } }],
	TabsRoot: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{
			name: 'activationMode',
			optional: true,
			type: { kind: 'enum', options: ['automatic', 'manual'] }
		},
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	TabsTriggerButton: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	TagButton: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['solid', 'outline', 'soft'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'dismissible', optional: true, type: { kind: 'boolean' } },
		{ name: 'onDismiss', optional: true, type: { kind: 'snippet' } }
	],
	TagsInputInput: [{ name: 'placeholder', optional: true, type: { kind: 'string' } }],
	TagsInputRoot: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'allowDuplicates', optional: true, type: { kind: 'boolean' } },
		{ name: 'maxTags', optional: true, type: { kind: 'number' } },
		{ name: 'onValueChange', optional: true, type: { kind: 'snippet' } }
	],
	TagsInputTag: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'index', optional: false, type: { kind: 'number' } }
	],
	TagsInputTagDeleteButton: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'index', optional: false, type: { kind: 'number' } }
	],
	Text: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'label'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['default', 'muted', 'secondary'] }
		},
		{ name: 'as', optional: true, type: { kind: 'enum', options: ['p', 'span', 'div'] } },
		{ name: 'font', optional: true, type: { kind: 'enum', options: ['sans', 'mono'] } },
		{
			name: 'maxMeasure',
			optional: true,
			type: { kind: 'enum', options: ['narrow', 'default', 'wide'] }
		},
		{
			name: 'weight',
			optional: true,
			type: { kind: 'enum', options: ['normal', 'medium', 'semibold', 'bold'] }
		}
	],
	Textarea: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	ThemeToggle: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'moonIcon', optional: true, type: { kind: 'snippet' } },
		{ name: 'storageKey', optional: true, type: { kind: 'string' } },
		{ name: 'sunIcon', optional: true, type: { kind: 'snippet' } }
	],
	TimeInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	TimelineRoot: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal'] }
		}
	],
	TimelineTime: [{ name: 'datetime', optional: true, type: { kind: 'string' } }],
	ToastProvider: [
		{
			name: 'position',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'top-right',
					'top-left',
					'bottom-right',
					'bottom-left',
					'top-center',
					'bottom-center'
				]
			}
		}
	],
	ToastRoot: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['info', 'success', 'warning', 'error'] }
		},
		{ name: 'id', optional: false, type: { kind: 'string' } },
		{ name: 'persistent', optional: true, type: { kind: 'boolean' } },
		{ name: 'progress', optional: true, type: { kind: 'number' } }
	],
	ToggleButton: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'pressed', optional: true, type: { kind: 'boolean' } }
	],
	ToggleGroupItemButton: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	ToggleGroupRoot: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	ToolbarButton: [{ name: 'disabled', optional: true, type: { kind: 'boolean' } }],
	ToolbarLink: [{ name: 'href', optional: false, type: { kind: 'string' } }],
	ToolbarRoot: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	TooltipContent: [{ name: 'offset', optional: true, type: { kind: 'number' } }],
	TooltipRoot: [
		{ name: 'closeDelay', optional: true, type: { kind: 'number' } },
		{ name: 'openDelay', optional: true, type: { kind: 'number' } }
	],
	TourRoot: [
		{ name: 'active', optional: true, type: { kind: 'boolean' } },
		{ name: 'onComplete', optional: true, type: { kind: 'snippet' } }
	],
	TransferItem: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'key', optional: false, type: { kind: 'string' } },
		{ name: 'type', optional: false, type: { kind: 'enum', options: ['source', 'target'] } }
	],
	TransferListInput: [
		{ name: 'content', optional: true, type: { kind: 'snippet' } },
		{ name: 'filterable', optional: true, type: { kind: 'boolean' } },
		{ name: 'title', optional: true, type: { kind: 'string' } },
		{ name: 'type', optional: false, type: { kind: 'enum', options: ['source', 'target'] } }
	],
	TransferRoot: [{ name: 'onChange', optional: true, type: { kind: 'snippet' } }],
	TreeItem: [{ name: 'itemId', optional: false, type: { kind: 'string' } }],
	TreeRoot: [{ name: 'selectedItem', optional: true, type: { kind: 'string' } }],
	VideoEmbedButton: [
		{ name: 'aspectRatio', optional: true, type: { kind: 'string' } },
		{ name: 'autoplay', optional: true, type: { kind: 'boolean' } },
		{ name: 'playButton', optional: true, type: { kind: 'snippet' } },
		{ name: 'poster', optional: true, type: { kind: 'string' } },
		{
			name: 'provider',
			optional: true,
			type: { kind: 'enum', options: ['youtube', 'vimeo', 'native'] }
		},
		{ name: 'src', optional: false, type: { kind: 'string' } },
		{ name: 'title', optional: true, type: { kind: 'string' } }
	]
};
