// AUTO-GENERATED by scripts/extract-feedback-schemas.ts
// Source: packages/mcp/src/spec.json. Re-run the script when that changes.

export type SchemaFieldType =
	| { kind: 'enum'; options: string[] }
	| { kind: 'boolean' }
	| { kind: 'number' }
	| { kind: 'string' }
	| { kind: 'snippet' };

export type SchemaField = {
	name: string;
	optional: boolean;
	type: SchemaFieldType;
};

export const COMPONENT_SCHEMAS: Record<string, SchemaField[]> = {
	Accordion: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	Adjust: [
		{ name: 'blur', optional: true, type: { kind: 'number' } },
		{ name: 'brightness', optional: true, type: { kind: 'number' } },
		{ name: 'contrast', optional: true, type: { kind: 'number' } },
		{ name: 'grayscale', optional: true, type: { kind: 'number' } },
		{ name: 'hueRotate', optional: true, type: { kind: 'number' } },
		{ name: 'invert', optional: true, type: { kind: 'number' } },
		{ name: 'saturate', optional: true, type: { kind: 'number' } },
		{ name: 'sepia', optional: true, type: { kind: 'number' } }
	],
	AffixGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'invalid', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Alert: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['info', 'success', 'warning', 'error'] }
		},
		{ name: 'description', optional: true, type: { kind: 'snippet' } },
		{ name: 'dismissible', optional: true, type: { kind: 'boolean' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'title', optional: true, type: { kind: 'snippet' } }
	],
	AlertDialog: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	AlphaSlider: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	AppFrame: [
		{ name: 'actions', optional: true, type: { kind: 'snippet' } },
		{ name: 'title', optional: true, type: { kind: 'string' } }
	],
	AspectRatio: [{ name: 'ratio', optional: true, type: { kind: 'number' } }],
	Aurora: [
		{
			name: 'colorSpace',
			optional: true,
			type: { kind: 'enum', options: ['srgb', 'oklch', 'oklab'] }
		},
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'layerOpacity', optional: true, type: { kind: 'number' } },
		{ name: 'motion', optional: true, type: { kind: 'enum', options: ['auto', 'never'] } },
		{ name: 'speed', optional: true, type: { kind: 'enum', options: ['slow', 'normal', 'fast'] } },
		{ name: 'waviness', optional: true, type: { kind: 'number' } }
	],
	Avatar: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'alt', optional: true, type: { kind: 'string' } },
		{ name: 'badge', optional: true, type: { kind: 'snippet' } },
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{ name: 'shape', optional: true, type: { kind: 'enum', options: ['circle', 'square'] } },
		{ name: 'src', optional: true, type: { kind: 'string' } },
		{
			name: 'status',
			optional: true,
			type: { kind: 'enum', options: ['online', 'offline', 'busy', 'away'] }
		}
	],
	AvatarGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'count', optional: true, type: { kind: 'number' } },
		{ name: 'label', optional: true, type: { kind: 'string' } },
		{ name: 'maxVisible', optional: true, type: { kind: 'number' } },
		{ name: 'overlap', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'status',
			optional: true,
			type: { kind: 'enum', options: ['online', 'offline', 'busy', 'away'] }
		}
	],
	Backdrop: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'invisible', optional: true, type: { kind: 'boolean' } }
	],
	Badge: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['solid', 'outline', 'soft', 'dot'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'pulse', optional: true, type: { kind: 'boolean' } }
	],
	Beam: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	BorderBeam: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'line'] } },
		{ name: 'active', optional: true, type: { kind: 'boolean' } },
		{ name: 'brightness', optional: true, type: { kind: 'number' } },
		{
			name: 'colorVariant',
			optional: true,
			type: { kind: 'enum', options: ['colorful', 'mono', 'ocean', 'sunset'] }
		},
		{ name: 'duration', optional: true, type: { kind: 'number' } },
		{ name: 'hueRange', optional: true, type: { kind: 'number' } },
		{ name: 'saturation', optional: true, type: { kind: 'number' } },
		{ name: 'staticColors', optional: true, type: { kind: 'boolean' } },
		{ name: 'strength', optional: true, type: { kind: 'number' } },
		{ name: 'theme', optional: true, type: { kind: 'enum', options: ['auto', 'light', 'dark'] } }
	],
	Button: [
		{
			name: 'variant',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'solid',
					'outline',
					'ghost',
					'soft',
					'secondary',
					'link',
					'bare',
					'trigger',
					'nav',
					'tab',
					'toggle',
					'pill'
				]
			}
		},
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['sm', 'md', 'lg', 'icon', 'icon-sm', 'icon-lg'] }
		},
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['primary', 'danger', 'ink'] }
		},
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'href', optional: true, type: { kind: 'string' } },
		{ name: 'rel', optional: true, type: { kind: 'string' } },
		{ name: 'target', optional: true, type: { kind: 'string' } },
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['button', 'submit', 'reset'] } }
	],
	ButtonGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Calendar: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	Carousel: [
		{ name: 'autoplay', optional: true, type: { kind: 'enum', options: ['false'] } },
		{ name: 'loop', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Chart: [
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'summary', optional: true, type: { kind: 'string' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	ChatMessage: [
		{ name: 'avatar', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{
			name: 'role',
			optional: true,
			type: { kind: 'enum', options: ['user', 'assistant', 'system'] }
		},
		{ name: 'timestamp', optional: true, type: { kind: 'string' } },
		{ name: 'typing', optional: true, type: { kind: 'boolean' } }
	],
	ChatThread: [
		{ name: 'messageCount', optional: false, type: { kind: 'number' } },
		{ name: 'scrollKey', optional: true, type: { kind: 'number' } }
	],
	Checkbox: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'checked', optional: true, type: { kind: 'boolean' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'indeterminate', optional: true, type: { kind: 'boolean' } }
	],
	Chip: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['solid', 'outline', 'soft'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'href', optional: true, type: { kind: 'string' } },
		{ name: 'rel', optional: true, type: { kind: 'string' } },
		{ name: 'selected', optional: true, type: { kind: 'boolean' } },
		{ name: 'target', optional: true, type: { kind: 'string' } },
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['button', 'submit', 'reset'] } }
	],
	ChipGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'gap', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'justify',
			optional: true,
			type: { kind: 'enum', options: ['start', 'center', 'end', 'between'] }
		},
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	ChromaticAberration: [
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{ name: 'offset', optional: true, type: { kind: 'number' } }
	],
	ChromaticShift: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{ name: 'channels', optional: true, type: { kind: 'enum', options: ['rgb', 'rb'] } },
		{ name: 'offset', optional: true, type: { kind: 'number' } },
		{
			name: 'trigger',
			optional: true,
			type: { kind: 'enum', options: ['hover', 'always', 'none'] }
		}
	],
	Clipboard: [
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'timeout', optional: true, type: { kind: 'number' } }
	],
	CodeBlock: [
		{ name: 'code', optional: false, type: { kind: 'string' } },
		{ name: 'language', optional: true, type: { kind: 'string' } },
		{ name: 'shell', optional: true, type: { kind: 'snippet' } },
		{ name: 'showCopyButton', optional: true, type: { kind: 'boolean' } },
		{ name: 'showLineNumbers', optional: true, type: { kind: 'boolean' } }
	],
	Collapsible: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } }
	],
	ColorPicker: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'alpha', optional: true, type: { kind: 'number' } },
		{ name: 'areaHeight', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	Combobox: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	CommandPalette: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Container: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['sm', 'md', 'lg', 'xl', 'full'] }
		},
		{ name: 'padding', optional: true, type: { kind: 'boolean' } }
	],
	ContextMenu: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	DataGrid: [
		{ name: 'actionBar', optional: true, type: { kind: 'snippet' } },
		{ name: 'pageSize', optional: true, type: { kind: 'number' } },
		{ name: 'selectable', optional: true, type: { kind: 'boolean' } },
		{ name: 'striped', optional: true, type: { kind: 'boolean' } }
	],
	DateField: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	DatePicker: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	DateRangePicker: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	DateTimeInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	Diagram: [
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	Dialog: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Displacement: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{ name: 'scale', optional: true, type: { kind: 'number' } },
		{
			name: 'turbulence',
			optional: true,
			type: { kind: 'enum', options: ['gentle', 'medium', 'rough'] }
		}
	],
	DragAndDrop: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal'] }
		}
	],
	Drawer: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{
			name: 'side',
			optional: true,
			type: { kind: 'enum', options: ['top', 'right', 'bottom', 'left'] }
		}
	],
	DropZone: [{ name: 'accept', optional: true, type: { kind: 'string' } }],
	DropdownMenu: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Field: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'error', optional: true, type: { kind: 'string' } },
		{ name: 'nestRadius', optional: true, type: { kind: 'boolean' } },
		{ name: 'required', optional: true, type: { kind: 'boolean' } }
	],
	FileSelect: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'accept', optional: true, type: { kind: 'string' } },
		{ name: 'directory', optional: true, type: { kind: 'boolean' } }
	],
	FileUpload: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'accept', optional: true, type: { kind: 'string' } },
		{ name: 'maxFiles', optional: true, type: { kind: 'number' } },
		{ name: 'maxSize', optional: true, type: { kind: 'number' } },
		{ name: 'multiple', optional: true, type: { kind: 'boolean' } }
	],
	FlipCard: [
		{
			name: 'direction',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'flipped', optional: true, type: { kind: 'boolean' } },
		{ name: 'trigger', optional: true, type: { kind: 'enum', options: ['hover', 'click'] } }
	],
	FloatButton: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['bottom-right', 'bottom-left'] }
		}
	],
	FocusTrap: [
		{ name: 'active', optional: true, type: { kind: 'boolean' } },
		{ name: 'initialFocus', optional: true, type: { kind: 'string' } },
		{ name: 'returnFocus', optional: true, type: { kind: 'boolean' } }
	],
	FormatBytes: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{
			name: 'display',
			optional: true,
			type: { kind: 'enum', options: ['short', 'long', 'narrow'] }
		},
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'unit', optional: true, type: { kind: 'enum', options: ['byte', 'bit'] } }
	],
	FormatDate: [
		{
			name: 'dateStyle',
			optional: true,
			type: { kind: 'enum', options: ['full', 'long', 'medium', 'short'] }
		},
		{ name: 'day', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{ name: 'era', optional: true, type: { kind: 'enum', options: ['long', 'short', 'narrow'] } },
		{ name: 'hour', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'hourCycle',
			optional: true,
			type: { kind: 'enum', options: ['h11', 'h12', 'h23', 'h24'] }
		},
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'minute', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'month',
			optional: true,
			type: { kind: 'enum', options: ['numeric', '2-digit', 'long', 'short', 'narrow'] }
		},
		{ name: 'second', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } },
		{
			name: 'timeStyle',
			optional: true,
			type: { kind: 'enum', options: ['full', 'long', 'medium', 'short'] }
		},
		{ name: 'timeZone', optional: true, type: { kind: 'string' } },
		{ name: 'timeZoneName', optional: true, type: { kind: 'enum', options: ['long', 'short'] } },
		{
			name: 'weekday',
			optional: true,
			type: { kind: 'enum', options: ['long', 'short', 'narrow'] }
		},
		{ name: 'year', optional: true, type: { kind: 'enum', options: ['numeric', '2-digit'] } }
	],
	FormatNumber: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{ name: 'currency', optional: true, type: { kind: 'string' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'maximumFractionDigits', optional: true, type: { kind: 'number' } },
		{ name: 'maximumSignificantDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumFractionDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumIntegerDigits', optional: true, type: { kind: 'number' } },
		{ name: 'minimumSignificantDigits', optional: true, type: { kind: 'number' } },
		{
			name: 'notation',
			optional: true,
			type: { kind: 'enum', options: ['standard', 'scientific', 'engineering', 'compact'] }
		},
		{
			name: 'type',
			optional: true,
			type: { kind: 'enum', options: ['decimal', 'currency', 'percent', 'unit'] }
		},
		{ name: 'unit', optional: true, type: { kind: 'string' } }
	],
	Gauge: [
		{ name: 'value', optional: false, type: { kind: 'number' } },
		{ name: 'endAngle', optional: true, type: { kind: 'number' } },
		{ name: 'label', optional: true, type: { kind: 'snippet' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'startAngle', optional: true, type: { kind: 'number' } }
	],
	Glass: [
		{ name: 'blur', optional: true, type: { kind: 'number' } },
		{ name: 'saturation', optional: true, type: { kind: 'number' } },
		{ name: 'tint', optional: true, type: { kind: 'string' } }
	],
	Glow: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'radius', optional: true, type: { kind: 'number' } }
	],
	GodRays: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'rayCount', optional: true, type: { kind: 'number' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } }
	],
	GradientMesh: [
		{ name: 'interactive', optional: true, type: { kind: 'boolean' } },
		{ name: 'speed', optional: true, type: { kind: 'enum', options: ['slow', 'normal', 'fast'] } }
	],
	Halftone: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'angle', optional: true, type: { kind: 'number' } },
		{
			name: 'dotSize',
			optional: true,
			type: { kind: 'enum', options: ['fine', 'medium', 'coarse'] }
		},
		{ name: 'opacity', optional: true, type: { kind: 'number' } }
	],
	Heading: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'display'] } },
		{
			name: 'level',
			optional: true,
			type: { kind: 'enum', options: ['1', '2', '3', '4', '5', '6'] }
		},
		{
			name: 'maxMeasure',
			optional: true,
			type: { kind: 'enum', options: ['narrow', 'default', 'wide', 'false'] }
		}
	],
	Hero: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'align', optional: true, type: { kind: 'enum', options: ['center', 'left'] } },
		{ name: 'backgroundImage', optional: true, type: { kind: 'string' } },
		{ name: 'overlay', optional: true, type: { kind: 'boolean' } }
	],
	Hotkey: [
		{ name: 'enabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'keys', optional: false, type: { kind: 'string' } },
		{ name: 'preventDefault', optional: true, type: { kind: 'boolean' } }
	],
	HoverCard: [
		{ name: 'closeDelay', optional: true, type: { kind: 'number' } },
		{ name: 'openDelay', optional: true, type: { kind: 'number' } }
	],
	Icon: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg', 'xl'] }
		},
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['primary', 'muted', 'current'] }
		},
		{ name: 'label', optional: true, type: { kind: 'string' } }
	],
	Image: [
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{ name: 'fallbackSnippet', optional: true, type: { kind: 'snippet' } }
	],
	ImageComparison: [
		{ name: 'after', optional: false, type: { kind: 'snippet' } },
		{ name: 'before', optional: false, type: { kind: 'snippet' } },
		{ name: 'handle', optional: true, type: { kind: 'snippet' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'position', optional: true, type: { kind: 'number' } }
	],
	InfiniteScroll: [
		{ name: 'endMessage', optional: true, type: { kind: 'snippet' } },
		{ name: 'hasMore', optional: true, type: { kind: 'boolean' } },
		{ name: 'loading', optional: true, type: { kind: 'boolean' } },
		{ name: 'loadingIndicator', optional: true, type: { kind: 'snippet' } },
		{ name: 'rootMargin', optional: true, type: { kind: 'string' } }
	],
	Input: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'ghost'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'type', optional: true, type: { kind: 'string' } }
	],
	Label: [{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } }],
	Link: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'external', optional: true, type: { kind: 'boolean' } },
		{
			name: 'underline',
			optional: true,
			type: { kind: 'enum', options: ['always', 'hover', 'none'] }
		}
	],
	LinkPreview: [
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'closeDelay', optional: true, type: { kind: 'number' } },
		{ name: 'openDelay', optional: true, type: { kind: 'number' } }
	],
	List: [
		{ name: 'dense', optional: true, type: { kind: 'boolean' } },
		{ name: 'disablePadding', optional: true, type: { kind: 'boolean' } }
	],
	Listbox: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'multiple', optional: true, type: { kind: 'boolean' } }
	],
	LogoCloud: [
		{ name: 'align', optional: true, type: { kind: 'enum', options: ['start', 'center', 'end'] } },
		{ name: 'columns', optional: true, type: { kind: 'number' } },
		{ name: 'gap', optional: true, type: { kind: 'string' } }
	],
	LogoMark: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['brand', 'neutral', 'error', 'warning', 'success', 'info'] }
		},
		{ name: 'alt', optional: true, type: { kind: 'string' } },
		{ name: 'fallback', optional: true, type: { kind: 'string' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['square', 'rounded', 'circle'] }
		},
		{ name: 'src', optional: true, type: { kind: 'string' } }
	],
	Map: [
		{ name: 'mapStyle', optional: true, type: { kind: 'string' } },
		{ name: 'maxZoom', optional: true, type: { kind: 'number' } },
		{ name: 'minZoom', optional: true, type: { kind: 'number' } },
		{ name: 'zoom', optional: true, type: { kind: 'number' } }
	],
	MarkdownRenderer: [
		{ name: 'content', optional: false, type: { kind: 'string' } },
		{ name: 'dangerouslyAllowRawHtml', optional: true, type: { kind: 'boolean' } }
	],
	Marquee: [
		{
			name: 'direction',
			optional: true,
			type: { kind: 'enum', options: ['left', 'right', 'up', 'down'] }
		},
		{ name: 'fade', optional: true, type: { kind: 'boolean' } },
		{ name: 'gap', optional: true, type: { kind: 'string' } },
		{ name: 'pauseOnHover', optional: true, type: { kind: 'boolean' } },
		{ name: 'speed', optional: true, type: { kind: 'number' } }
	],
	MaskReveal: [
		{ name: 'direction', optional: true, type: { kind: 'enum', options: ['in', 'out'] } },
		{ name: 'duration', optional: true, type: { kind: 'number' } },
		{ name: 'once', optional: true, type: { kind: 'boolean' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['circle', 'linear', 'diagonal', 'diamond'] }
		},
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	MultiSelectCombobox: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'maxSelections', optional: true, type: { kind: 'number' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{ name: 'query', optional: true, type: { kind: 'string' } }
	],
	Noise: [
		{ name: 'animated', optional: true, type: { kind: 'boolean' } },
		{
			name: 'blend',
			optional: true,
			type: { kind: 'enum', options: ['soft-light', 'overlay', 'multiply'] }
		},
		{
			name: 'grain',
			optional: true,
			type: { kind: 'enum', options: ['fine', 'medium', 'coarse'] }
		},
		{ name: 'opacity', optional: true, type: { kind: 'number' } }
	],
	NotificationCenter: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	NumberInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	OptionPicker: [
		{ name: 'columns', optional: true, type: { kind: 'enum', options: ['1', '2', '3', '4'] } }
	],
	Pagination: [
		{ name: 'page', optional: true, type: { kind: 'number' } },
		{ name: 'totalPages', optional: false, type: { kind: 'number' } }
	],
	PhoneInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'defaultCountry', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	PinInput: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['outline', 'flushed'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'blurOnComplete', optional: true, type: { kind: 'boolean' } },
		{ name: 'length', optional: true, type: { kind: 'number' } },
		{ name: 'mask', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['numeric', 'alphanumeric'] } }
	],
	Popover: [{ name: 'open', optional: true, type: { kind: 'boolean' } }],
	Portal: [{ name: 'disabled', optional: true, type: { kind: 'boolean' } }],
	Progress: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['blue', 'green', 'red', 'yellow'] }
		},
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'max', optional: true, type: { kind: 'number' } }
	],
	ProgressRing: [
		{ name: 'size', optional: true, type: { kind: 'number' } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['primary', 'gray', 'green', 'red', 'yellow'] }
		},
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'indeterminate', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } }
	],
	PromptInput: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'actions', optional: true, type: { kind: 'snippet' } },
		{ name: 'submitLabel', optional: true, type: { kind: 'string' } }
	],
	QRCode: [
		{ name: 'size', optional: true, type: { kind: 'number' } },
		{ name: 'value', optional: false, type: { kind: 'string' } },
		{ name: 'bgColor', optional: true, type: { kind: 'string' } },
		{
			name: 'errorCorrection',
			optional: true,
			type: { kind: 'enum', options: ['L', 'M', 'Q', 'H'] }
		},
		{ name: 'fgColor', optional: true, type: { kind: 'string' } }
	],
	RadioGroup: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'required', optional: true, type: { kind: 'boolean' } }
	],
	RangeCalendar: [
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'locale', optional: true, type: { kind: 'string' } }
	],
	Rating: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'allowHalf', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'readonly', optional: true, type: { kind: 'boolean' } }
	],
	RelativeTime: [
		{ name: 'locale', optional: true, type: { kind: 'string' } },
		{ name: 'updateInterval', optional: true, type: { kind: 'number' } }
	],
	Reveal: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['fade', 'slide-up', 'scale-in', 'blur-up', 'mask-up'] }
		},
		{ name: 'delay', optional: true, type: { kind: 'number' } },
		{ name: 'duration', optional: true, type: { kind: 'number' } },
		{ name: 'once', optional: true, type: { kind: 'boolean' } },
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	RichTextEditor: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'readonly', optional: true, type: { kind: 'boolean' } }
	],
	ScrollArea: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal', 'both'] }
		}
	],
	ScrollToTop: [
		{
			name: 'position',
			optional: true,
			type: { kind: 'enum', options: ['bottom-right', 'bottom-left', 'bottom-center'] }
		},
		{ name: 'threshold', optional: true, type: { kind: 'number' } }
	],
	SegmentedControl: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Select: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'placeholder', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'open', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } }
	],
	SelectableTileGroup: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Separator: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['weak', 'strong'] } },
		{ name: 'decorative', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	ShaderCanvas: [
		{ name: 'aspectRatio', optional: true, type: { kind: 'string' } },
		{ name: 'fragmentShader', optional: true, type: { kind: 'string' } },
		{
			name: 'preset',
			optional: true,
			type: {
				kind: 'enum',
				options: [
					'gradient-flow',
					'particle-field',
					'wave-distortion',
					'mesh-gradient',
					'liquid-metal'
				]
			}
		},
		{ name: 'themeColors', optional: true, type: { kind: 'boolean' } }
	],
	Shimmer: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'duration', optional: true, type: { kind: 'number' } }
	],
	Sidebar: [
		{ name: 'collapsed', optional: true, type: { kind: 'boolean' } },
		{ name: 'side', optional: true, type: { kind: 'enum', options: ['left', 'right'] } }
	],
	Skeleton: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['text', 'circular', 'rectangular'] }
		},
		{ name: 'height', optional: true, type: { kind: 'string' } },
		{ name: 'width', optional: true, type: { kind: 'string' } }
	],
	Slider: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'pill'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'number' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'max', optional: true, type: { kind: 'number' } },
		{ name: 'min', optional: true, type: { kind: 'number' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'step', optional: true, type: { kind: 'number' } },
		{ name: 'valueLabel', optional: true, type: { kind: 'snippet' } }
	],
	Spacer: [
		{
			name: 'size',
			optional: true,
			type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'] }
		},
		{ name: 'axis', optional: true, type: { kind: 'enum', options: ['vertical', 'horizontal'] } }
	],
	Sparkline: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'filled', optional: true, type: { kind: 'boolean' } },
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{ name: 'highlightLast', optional: true, type: { kind: 'boolean' } },
		{ name: 'strokeWidth', optional: true, type: { kind: 'number' } },
		{ name: 'width', optional: true, type: { kind: 'number' } }
	],
	Spinner: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'color', optional: true, type: { kind: 'enum', options: ['primary', 'current'] } },
		{ name: 'label', optional: true, type: { kind: 'string' } }
	],
	Splitter: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Spotlight: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'followPointer', optional: true, type: { kind: 'boolean' } },
		{ name: 'intensity', optional: true, type: { kind: 'number' } },
		{ name: 'radius', optional: true, type: { kind: 'number' } }
	],
	StarRating: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['filled', 'outlined'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'label', optional: true, type: { kind: 'string' } },
		{ name: 'stars', optional: false, type: { kind: 'number' } }
	],
	StatCard: [
		{
			name: 'density',
			optional: true,
			type: { kind: 'enum', options: ['comfortable', 'compact'] }
		},
		{
			name: 'tone',
			optional: true,
			type: { kind: 'enum', options: ['neutral', 'info', 'success', 'warning', 'danger'] }
		}
	],
	Stepper: [
		{ name: 'activeStep', optional: true, type: { kind: 'number' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Svg: [{ name: 'viewBox', optional: true, type: { kind: 'string' } }],
	TableOfContents: [
		{ name: 'autoId', optional: true, type: { kind: 'boolean' } },
		{ name: 'headingSelector', optional: true, type: { kind: 'string' } },
		{ name: 'rootMargin', optional: true, type: { kind: 'string' } },
		{ name: 'selector', optional: true, type: { kind: 'string' } }
	],
	Tabs: [
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{
			name: 'activationMode',
			optional: true,
			type: { kind: 'enum', options: ['automatic', 'manual'] }
		},
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Tag: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['solid', 'outline', 'soft'] }
		},
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md'] } },
		{ name: 'dismissible', optional: true, type: { kind: 'boolean' } }
	],
	TagsInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'allowDuplicates', optional: true, type: { kind: 'boolean' } },
		{ name: 'maxTags', optional: true, type: { kind: 'number' } }
	],
	Text: [
		{ name: 'variant', optional: true, type: { kind: 'enum', options: ['default', 'label'] } },
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['xs', 'sm', 'md', 'lg'] } },
		{
			name: 'color',
			optional: true,
			type: { kind: 'enum', options: ['default', 'muted', 'secondary'] }
		},
		{ name: 'as', optional: true, type: { kind: 'enum', options: ['p', 'span', 'div'] } },
		{ name: 'font', optional: true, type: { kind: 'enum', options: ['sans', 'mono'] } },
		{
			name: 'maxMeasure',
			optional: true,
			type: { kind: 'enum', options: ['narrow', 'default', 'wide', 'false'] }
		},
		{
			name: 'weight',
			optional: true,
			type: { kind: 'enum', options: ['normal', 'medium', 'semibold', 'bold'] }
		}
	],
	Textarea: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } }
	],
	ThemeToggle: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'moonIcon', optional: true, type: { kind: 'snippet' } },
		{ name: 'storageKey', optional: true, type: { kind: 'string' } },
		{ name: 'sunIcon', optional: true, type: { kind: 'snippet' } }
	],
	TimeInput: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'value', optional: true, type: { kind: 'string' } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'name', optional: true, type: { kind: 'string' } },
		{ name: 'step', optional: true, type: { kind: 'number' } }
	],
	Timeline: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['vertical', 'horizontal'] }
		}
	],
	Toast: [
		{
			name: 'variant',
			optional: true,
			type: { kind: 'enum', options: ['info', 'success', 'warning', 'error'] }
		},
		{ name: 'id', optional: false, type: { kind: 'string' } },
		{ name: 'persistent', optional: true, type: { kind: 'boolean' } },
		{ name: 'progress', optional: true, type: { kind: 'number' } }
	],
	Toggle: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{ name: 'icon', optional: true, type: { kind: 'snippet' } },
		{ name: 'pressed', optional: true, type: { kind: 'boolean' } }
	],
	ToggleGroup: [
		{ name: 'size', optional: true, type: { kind: 'enum', options: ['sm', 'md', 'lg'] } },
		{ name: 'disabled', optional: true, type: { kind: 'boolean' } },
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		},
		{ name: 'type', optional: true, type: { kind: 'enum', options: ['single', 'multiple'] } }
	],
	Toolbar: [
		{
			name: 'orientation',
			optional: true,
			type: { kind: 'enum', options: ['horizontal', 'vertical'] }
		}
	],
	Tooltip: [
		{ name: 'closeDelay', optional: true, type: { kind: 'number' } },
		{ name: 'openDelay', optional: true, type: { kind: 'number' } }
	],
	Tour: [{ name: 'active', optional: true, type: { kind: 'boolean' } }],
	Tree: [{ name: 'selectedItem', optional: true, type: { kind: 'string' } }],
	User: [
		{ name: 'description', optional: true, type: { kind: 'string' } },
		{ name: 'name', optional: false, type: { kind: 'string' } }
	],
	VideoEmbed: [
		{ name: 'aspectRatio', optional: true, type: { kind: 'string' } },
		{ name: 'autoplay', optional: true, type: { kind: 'boolean' } },
		{ name: 'playButton', optional: true, type: { kind: 'snippet' } },
		{ name: 'poster', optional: true, type: { kind: 'string' } },
		{
			name: 'provider',
			optional: true,
			type: { kind: 'enum', options: ['youtube', 'vimeo', 'native'] }
		},
		{ name: 'src', optional: false, type: { kind: 'string' } },
		{ name: 'title', optional: true, type: { kind: 'string' } }
	],
	VirtualList: [{ name: 'overscan', optional: true, type: { kind: 'number' } }],
	WaveDivider: [
		{ name: 'color', optional: true, type: { kind: 'string' } },
		{ name: 'flip', optional: true, type: { kind: 'boolean' } },
		{ name: 'height', optional: true, type: { kind: 'number' } },
		{
			name: 'shape',
			optional: true,
			type: { kind: 'enum', options: ['wave', 'curve', 'angle', 'zigzag'] }
		}
	]
};
