import { readFileSync, readdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '..');
const changesetDir = resolve(repoRoot, '.changeset');
const configPath = resolve(changesetDir, 'config.json');

interface ChangesetConfig {
	ignore?: string[];
}

function sh(command: string): string {
	return execSync(command, { cwd: repoRoot, encoding: 'utf8' }).trim();
}

function findLastReleaseSha(): string {
	const sha = sh('git log --grep="^chore: version packages" -n 1 --pretty=format:%H');
	if (!sha) {
		console.error('check-changeset-required: no prior "chore: version packages" commit found');
		process.exit(1);
	}
	return sha;
}

function getChangedFiles(baseSha: string): string[] {
	const output = sh(`git diff --name-only ${baseSha}..HEAD`);
	return output ? output.split('\n') : [];
}

// These files are regenerated by the version step (see root `version` script)
// or are otherwise build artifacts that shouldn't trigger the changeset gate
// on their own. A real change always lands alongside a source-code edit that
// will already trip the gate.
const GENERATED_FILES = new Set([
	'packages/mcp/src/spec.json',
	'packages/mcp/src/architecture.json',
	'packages/mcp/src/contract.v1.json',
	'packages/mcp/src/contract.v1.schema.json',
	'packages/mcp/src/theme-tokens.generated.json'
]);

// Paths that live under packages/ but aren't part of the published tarball,
// so they don't need a changeset on their own. Pure source/test/tooling edits
// still bundled with a real change will show the real file alongside them
// and trip the gate correctly.
const NON_PUBLISHABLE_PATTERNS: readonly RegExp[] = [
	/\/__tests__\//,
	/\.test\.[tj]sx?$/,
	/\.spec\.[tj]sx?$/,
	/\/tsconfig[^/]*\.json$/,
	/\/tsbuildinfo$/,
	/\.tsbuildinfo$/,
	/\/CHANGELOG\.md$/
];

function isNonPublishablePath(path: string): boolean {
	return NON_PUBLISHABLE_PATTERNS.some((re) => re.test(path));
}

function getPackageRootFromPath(path: string): string | null {
	if (GENERATED_FILES.has(path)) return null;
	if (isNonPublishablePath(path)) return null;
	const match = path.match(/^packages\/([^/]+)\//);
	return match ? match[1]! : null;
}

function getPackageName(packageRoot: string): string | null {
	try {
		const pkg = JSON.parse(
			readFileSync(resolve(repoRoot, 'packages', packageRoot, 'package.json'), 'utf8')
		) as { name?: string; private?: boolean };
		if (pkg.private) return null;
		return pkg.name ?? null;
	} catch {
		return null;
	}
}

function getPendingChangesets(): string[] {
	return readdirSync(changesetDir).filter(
		(entry) => entry.endsWith('.md') && entry !== 'README.md'
	);
}

const config = JSON.parse(readFileSync(configPath, 'utf8')) as ChangesetConfig;
const ignored = new Set(config.ignore ?? []);

const baseSha = findLastReleaseSha();
const changedFiles = getChangedFiles(baseSha);

const touchedPackages = new Set<string>();
for (const file of changedFiles) {
	const root = getPackageRootFromPath(file);
	if (!root) continue;
	const name = getPackageName(root);
	if (!name) continue;
	if (ignored.has(name)) continue;
	touchedPackages.add(name);
}

if (touchedPackages.size === 0) {
	console.log('check-changeset-required: no publishable package changes since last release');
	process.exit(0);
}

const pending = getPendingChangesets();
if (pending.length > 0) {
	console.log(
		`check-changeset-required: ${pending.length} pending changeset(s) cover the following packages:`
	);
	for (const name of [...touchedPackages].sort()) console.log(`  - ${name}`);
	process.exit(0);
}

console.error(
	`check-changeset-required: ${touchedPackages.size} publishable package(s) changed since ${baseSha.slice(0, 8)} but no changeset is staged.`
);
for (const name of [...touchedPackages].sort()) console.error(`  - ${name}`);
console.error('');
console.error('Run `bun run changeset` and commit the generated `.changeset/*.md` file.');
process.exit(1);
