#!/usr/bin/env bun
// Generates packages/feedback/src/components/component-names.ts from
// @dryui/mcp's spec.json. The widget's "Add component" picker reads the
// resulting `COMPONENT_NAMES` / `COMPONENT_CATEGORIES` exports — the spec is
// the canonical name + category source (see CONTEXT.md "Spec"). Re-run
// `bun packages/mcp/src/generate-spec.ts` first if the spec is stale.
//
// Run: bun scripts/extract-feedback-names.ts

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SPEC_PATH = join(import.meta.dir, '..', 'packages', 'mcp', 'src', 'spec.json');
const COMPONENT_DEFAULTS_DIR = join(
	import.meta.dir,
	'..',
	'packages',
	'feedback',
	'src',
	'components',
	'component-defaults'
);
const OUT = join(
	import.meta.dir,
	'..',
	'packages',
	'feedback',
	'src',
	'components',
	'component-names.ts'
);

interface ComponentDef {
	category: string;
	import: string;
}

interface Spec {
	components?: Record<string, ComponentDef>;
}

// Categories the widget's picker recognizes. Spec uses these as bare strings;
// listing them here lets the generated file ship a typed union matching the
// spec slice we keep (everything imported from `@dryui/ui`).
const CATEGORIES = [
	'action',
	'display',
	'feedback',
	'form',
	'input',
	'interaction',
	'layout',
	'navigation',
	'overlay',
	'theme',
	'utility',
	'visual'
] as const;
type ComponentCategory = (typeof CATEGORIES)[number];

// Order the picker uses to sort category groups. Action/form/input/nav/overlay
// first (the high-traffic groups), then layout/display/feedback, then visual,
// then the long-tail meta groups. Theme sits with utility because TokenScope
// is a wrapper, not a piece of UI to drop on a page.
const CATEGORY_ORDER: ComponentCategory[] = [
	'action',
	'form',
	'input',
	'navigation',
	'overlay',
	'layout',
	'display',
	'feedback',
	'visual',
	'interaction',
	'theme',
	'utility'
];

// Title-case label per category for the picker UI.
const CATEGORY_LABELS: Record<ComponentCategory, string> = {
	action: 'Action',
	form: 'Form',
	input: 'Input',
	navigation: 'Navigation',
	overlay: 'Overlay',
	layout: 'Layout',
	display: 'Display',
	feedback: 'Feedback',
	visual: 'Visual',
	interaction: 'Interaction',
	theme: 'Theme',
	utility: 'Utility'
};

// Widget-only catalog overlay: components the picker exposes that the spec
// does not. `Motion` is a widget umbrella over `Enter` / `Exit` / `Stagger`
// that the picker treats as one entry; it has its own component-default in
// `components/component-defaults/motion.svelte`.
const WIDGET_OVERLAY: Record<string, ComponentCategory> = {
	Motion: 'display'
};

function isCategory(value: string): value is ComponentCategory {
	return (CATEGORIES as readonly string[]).includes(value);
}

function pascalFromKebab(kebab: string): string {
	return kebab
		.split('-')
		.map((part) => (part ? part[0]!.toUpperCase() + part.slice(1) : ''))
		.join('');
}

// Pre-built component-default templates the widget can drop on the page.
// Used as the gating signal for `@dryui/primitives` entries: spec exposes
// many primitives that have no widget template (and `@dryui/ui` doesn't
// re-export them), so listing them in the picker would silently fail at
// render time. UI exports ride the `import('@dryui/ui')` fallback in
// `feedback.svelte`, so they don't need a default to be pickable.
const COMPONENT_DEFAULT_NAMES = new Set(
	readdirSync(COMPONENT_DEFAULTS_DIR)
		.filter((file) => file.endsWith('.svelte'))
		.map((file) => pascalFromKebab(file.slice(0, -'.svelte'.length)))
);

const spec: Spec = JSON.parse(readFileSync(SPEC_PATH, 'utf8'));
const componentCategories: Record<string, ComponentCategory> = {};

for (const [name, component] of Object.entries(spec.components ?? {})) {
	// `@dryui/ui` exports are always pickable: the widget falls back to
	// `import('@dryui/ui')[name]` when no template is registered.
	// `@dryui/primitives` exports are only pickable when a hand-authored
	// template exists in `components/component-defaults/`, since UI does not
	// re-export them.
	if (component.import === '@dryui/ui') {
		// always include
	} else if (component.import === '@dryui/primitives') {
		if (!COMPONENT_DEFAULT_NAMES.has(name)) continue;
	} else {
		continue;
	}
	if (!isCategory(component.category)) {
		throw new Error(
			`Component "${name}" has unknown category "${component.category}". ` +
				`Add it to CATEGORIES in scripts/extract-feedback-names.ts or fix the spec.`
		);
	}
	componentCategories[name] = component.category;
}

for (const [name, category] of Object.entries(WIDGET_OVERLAY)) {
	if (componentCategories[name]) {
		throw new Error(
			`Overlay collides with spec entry "${name}". Drop it from WIDGET_OVERLAY ` +
				`in scripts/extract-feedback-names.ts.`
		);
	}
	componentCategories[name] = category;
}

const sortedNames = Object.keys(componentCategories).sort();

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/extract-feedback-names.ts');
lines.push('// Source: packages/mcp/src/spec.json (Spec, see CONTEXT.md). Re-run the script');
lines.push('// when component metadata changes. Spec entries imported from @dryui/ui plus');
lines.push('// the widget-only overlay (e.g. Motion umbrella) feed the picker.');
lines.push('');
lines.push('export type ComponentCategory =');
for (let index = 0; index < CATEGORIES.length; index++) {
	const category = CATEGORIES[index];
	const suffix = index === CATEGORIES.length - 1 ? ';' : '';
	lines.push(`\t| '${category}'${suffix}`);
}
lines.push('');
lines.push('export const CATEGORY_ORDER: ComponentCategory[] = [');
for (let index = 0; index < CATEGORY_ORDER.length; index++) {
	const suffix = index === CATEGORY_ORDER.length - 1 ? '' : ',';
	lines.push(`\t'${CATEGORY_ORDER[index]}'${suffix}`);
}
lines.push('];');
lines.push('');
lines.push('export const CATEGORY_LABELS: Record<ComponentCategory, string> = {');
for (let index = 0; index < CATEGORIES.length; index++) {
	const category = CATEGORIES[index];
	const suffix = index === CATEGORIES.length - 1 ? '' : ',';
	lines.push(`\t${category}: '${CATEGORY_LABELS[category]}'${suffix}`);
}
lines.push('};');
lines.push('');
lines.push('export const COMPONENT_CATEGORIES: Record<string, ComponentCategory> = {');
for (let index = 0; index < sortedNames.length; index++) {
	const name = sortedNames[index];
	const suffix = index === sortedNames.length - 1 ? '' : ',';
	lines.push(`\t${name}: '${componentCategories[name]}'${suffix}`);
}
lines.push('};');
lines.push('');
lines.push(
	'export const COMPONENT_NAMES = Object.keys(COMPONENT_CATEGORIES).sort() as readonly string[];'
);
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${sortedNames.length} component names to ${OUT}`);
