#!/usr/bin/env bun
// Generates packages/feedback/src/components/component-schemas.ts from
// @dryui/mcp's spec.json (which already parses every component's typed Props
// interface). The feedback widget's "Edit props" panel consumes this slim
// schema to render form controls — keep spec.json in sync first if it's
// stale (`bun packages/mcp/src/generate-spec.ts`).
//
// Run: bun scripts/extract-feedback-schemas.ts

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SPEC_PATH = join(import.meta.dir, '..', 'packages', 'mcp', 'src', 'spec.json');
const OUT = join(
	import.meta.dir,
	'..',
	'packages',
	'feedback',
	'src',
	'components',
	'component-schemas.ts'
);

type SchemaFieldType =
	| { kind: 'enum'; options: string[] }
	| { kind: 'boolean' }
	| { kind: 'number' }
	| { kind: 'string' }
	| { kind: 'snippet' };

type SchemaField = {
	name: string;
	optional: boolean;
	type: SchemaFieldType;
};

interface PropDef {
	type: string;
	required: boolean;
	acceptedValues?: string[];
}

interface ComponentDef {
	props?: Record<string, PropDef>;
	compound?: boolean;
	parts?: Record<string, { props?: Record<string, PropDef> }>;
}

interface Spec {
	components?: Record<string, ComponentDef>;
}

const SKIP_PROPS = new Set(['ref', 'class', 'className', 'children', 'style']);
const PROP_PRIORITY: Record<string, number> = {
	variant: 0,
	size: 1,
	color: 2,
	value: 3,
	placeholder: 4,
	checked: 5,
	disabled: 6,
	open: 7
};

function classifyProp(prop: PropDef): SchemaFieldType | null {
	const cleanType = prop.type.replace(/\s*\|\s*(undefined|null)\b/g, '').trim();
	if (/\bSnippet\b/.test(cleanType)) return { kind: 'snippet' };
	if (prop.acceptedValues && prop.acceptedValues.length > 0) {
		const options = prop.acceptedValues.filter((v) => v !== 'null' && v !== 'undefined');
		if (options.length > 0) return { kind: 'enum', options };
	}
	if (/^boolean$/.test(cleanType)) return { kind: 'boolean' };
	if (/^number$/.test(cleanType)) return { kind: 'number' };
	if (/^string$/.test(cleanType) || /string\s*&\s*\{\s*\}/.test(cleanType)) {
		return { kind: 'string' };
	}
	return null;
}

function fieldOrder(a: SchemaField, b: SchemaField): number {
	const pa = PROP_PRIORITY[a.name] ?? 999;
	const pb = PROP_PRIORITY[b.name] ?? 999;
	if (pa !== pb) return pa - pb;
	return a.name.localeCompare(b.name);
}

const spec: Spec = JSON.parse(readFileSync(SPEC_PATH, 'utf8'));
const schemas: Record<string, SchemaField[]> = {};

function propsFor(component: ComponentDef): Record<string, PropDef> {
	if (!component.compound) return component.props ?? {};
	return component.parts?.Root?.props ?? {};
}

for (const [name, component] of Object.entries(spec.components ?? {})) {
	const fields: SchemaField[] = [];
	for (const [propName, prop] of Object.entries(propsFor(component))) {
		if (SKIP_PROPS.has(propName)) continue;
		const type = classifyProp(prop);
		if (!type) continue;
		fields.push({ name: propName, optional: !prop.required, type });
	}
	if (fields.length === 0) continue;
	fields.sort(fieldOrder);
	schemas[name] = fields;
}

const sortedNames = Object.keys(schemas).sort();
const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/extract-feedback-schemas.ts');
lines.push('// Source: packages/mcp/src/spec.json. Re-run the script when that changes.');
lines.push('');
lines.push('export type SchemaFieldType =');
lines.push("\t| { kind: 'enum'; options: string[] }");
lines.push("\t| { kind: 'boolean' }");
lines.push("\t| { kind: 'number' }");
lines.push("\t| { kind: 'string' }");
lines.push("\t| { kind: 'snippet' };");
lines.push('');
lines.push('export type SchemaField = {');
lines.push('\tname: string;');
lines.push('\toptional: boolean;');
lines.push('\ttype: SchemaFieldType;');
lines.push('};');
lines.push('');
lines.push('export const COMPONENT_SCHEMAS: Record<string, SchemaField[]> = {');
for (const name of sortedNames) {
	lines.push(`\t${JSON.stringify(name)}: [`);
	for (const field of schemas[name]) {
		lines.push(`\t\t${JSON.stringify(field)},`);
	}
	lines.push('\t],');
}
lines.push('};');
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote schemas for ${sortedNames.length} components to ${OUT}`);
