#!/usr/bin/env bun
// Generates packages/feedback/src/components/component-names.ts by walking the
// per-component `*.meta.ts` files under packages/ui/src and
// packages/primitives/src. The widget's "Add component" picker reads the
// resulting `COMPONENT_NAMES` / `COMPONENT_CATEGORIES` exports.
//
// Run: bun scripts/extract-feedback-names.ts

import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const repoRoot = join(import.meta.dir, '..');
const META_ROOTS = [
	join(repoRoot, 'packages', 'ui', 'src'),
	join(repoRoot, 'packages', 'primitives', 'src')
];
const COMPONENT_DEFAULTS_DIR = join(
	repoRoot,
	'packages',
	'feedback',
	'src',
	'components',
	'component-defaults'
);
const OUT = join(repoRoot, 'packages', 'feedback', 'src', 'components', 'component-names.ts');

// Categories the widget's picker recognizes. Listed here so the generated file
// ships a typed union, and so a meta file with an unknown category fails the
// generator instead of leaking through to the picker.
const CATEGORIES = [
	'action',
	'display',
	'feedback',
	'form',
	'input',
	'interaction',
	'layout',
	'navigation',
	'overlay',
	'theme',
	'utility',
	'visual'
] as const;
type ComponentCategory = (typeof CATEGORIES)[number];

// Order the picker uses to sort category groups. Action/form/input/nav/overlay
// first (the high-traffic groups), then layout/display/feedback, then visual,
// then the long-tail meta groups. Theme sits with utility because TokenScope
// is a wrapper, not a piece of UI to drop on a page.
const CATEGORY_ORDER: ComponentCategory[] = [
	'action',
	'form',
	'input',
	'navigation',
	'overlay',
	'layout',
	'display',
	'feedback',
	'visual',
	'interaction',
	'theme',
	'utility'
];

// Title-case label per category for the picker UI.
const CATEGORY_LABELS: Record<ComponentCategory, string> = {
	action: 'Action',
	form: 'Form',
	input: 'Input',
	navigation: 'Navigation',
	overlay: 'Overlay',
	layout: 'Layout',
	display: 'Display',
	feedback: 'Feedback',
	visual: 'Visual',
	interaction: 'Interaction',
	theme: 'Theme',
	utility: 'Utility'
};

interface MetaModule {
	default?: {
		name?: unknown;
		category?: unknown;
		surface?: unknown;
	};
}

function isCategory(value: unknown): value is ComponentCategory {
	return typeof value === 'string' && (CATEGORIES as readonly string[]).includes(value);
}

function pascalFromKebab(kebab: string): string {
	return kebab
		.split('-')
		.map((part) => (part ? part[0]!.toUpperCase() + part.slice(1) : ''))
		.join('');
}

function findMetaFiles(root: string): string[] {
	const out: string[] = [];
	let entries: string[];
	try {
		entries = readdirSync(root);
	} catch {
		return out;
	}
	for (const entry of entries) {
		const full = join(root, entry);
		let stat;
		try {
			stat = statSync(full);
		} catch {
			continue;
		}
		if (stat.isDirectory()) {
			if (entry === 'node_modules' || entry === '__tests__') continue;
			out.push(...findMetaFiles(full));
		} else if (stat.isFile() && entry.endsWith('.meta.ts')) {
			out.push(full);
		}
	}
	return out;
}

// Pre-built component-default templates the widget can drop on the page.
// Used as the gating signal for primitive components: many primitives don't
// have a widget template and `@dryui/ui` doesn't re-export them, so listing
// them in the picker would silently fail at render time. UI exports ride the
// `import('@dryui/ui')[name]` fallback in `feedback.svelte`, so they don't
// need a default to be pickable.
const COMPONENT_DEFAULT_NAMES = new Set(
	readdirSync(COMPONENT_DEFAULTS_DIR)
		.filter((file) => file.endsWith('.svelte'))
		.map((file) => pascalFromKebab(file.slice(0, -'.svelte'.length)))
);

const componentCategories: Record<string, ComponentCategory> = {};

for (const root of META_ROOTS) {
	const files = findMetaFiles(root);
	for (const file of files) {
		const mod = (await import(pathToFileURL(file).href)) as MetaModule;
		const meta = mod.default;
		if (!meta || typeof meta.name !== 'string') {
			throw new Error(`extract-feedback-names: ${file} has no usable default export`);
		}
		const name = meta.name;
		const isPrimitive = meta.surface === 'primitive';
		// UI exports always pickable, primitives only when a hand-rolled default
		// template exists.
		if (isPrimitive && !COMPONENT_DEFAULT_NAMES.has(name)) continue;
		if (!isCategory(meta.category)) {
			throw new Error(
				`Component "${name}" in ${file} has unknown category "${String(meta.category)}". ` +
					`Add it to CATEGORIES in scripts/extract-feedback-names.ts or fix the meta file.`
			);
		}
		if (componentCategories[name]) {
			throw new Error(
				`Duplicate component "${name}" found in ${file}. Component names must be unique across packages.`
			);
		}
		componentCategories[name] = meta.category;
	}
}

const sortedNames = Object.keys(componentCategories).sort();

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/extract-feedback-names.ts');
lines.push('// Source: packages/ui/src and packages/primitives/src `*.meta.ts` files.');
lines.push('// Re-run the script when component metadata changes.');
lines.push('');
lines.push('export type ComponentCategory =');
for (let index = 0; index < CATEGORIES.length; index++) {
	const category = CATEGORIES[index];
	const suffix = index === CATEGORIES.length - 1 ? ';' : '';
	lines.push(`\t| '${category}'${suffix}`);
}
lines.push('');
lines.push('export const CATEGORY_ORDER: ComponentCategory[] = [');
for (let index = 0; index < CATEGORY_ORDER.length; index++) {
	const suffix = index === CATEGORY_ORDER.length - 1 ? '' : ',';
	lines.push(`\t'${CATEGORY_ORDER[index]}'${suffix}`);
}
lines.push('];');
lines.push('');
lines.push('export const CATEGORY_LABELS: Record<ComponentCategory, string> = {');
for (let index = 0; index < CATEGORIES.length; index++) {
	const category = CATEGORIES[index];
	const suffix = index === CATEGORIES.length - 1 ? '' : ',';
	lines.push(`\t${category}: '${CATEGORY_LABELS[category]}'${suffix}`);
}
lines.push('};');
lines.push('');
lines.push('export const COMPONENT_CATEGORIES: Record<string, ComponentCategory> = {');
for (let index = 0; index < sortedNames.length; index++) {
	const name = sortedNames[index];
	const suffix = index === sortedNames.length - 1 ? '' : ',';
	lines.push(`\t${name}: '${componentCategories[name]}'${suffix}`);
}
lines.push('};');
lines.push('');
lines.push(
	'export const COMPONENT_NAMES = Object.keys(COMPONENT_CATEGORIES).sort() as readonly string[];'
);
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${sortedNames.length} component names to ${OUT}`);
